name: online_shop_flutter
description: "Online shop demo project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  flutter_riverpod: ^2.5.1
  get_it: ^7.6.7
  talker_flutter: ^3.2.0
  talker_dio_logger: ^2.4.0
  intl: ^0.19.0
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  go_router_builder: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
